version: '2.1'
services:
  server:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    container_name: 'server'
  api:
    build: .
    command: npm run start:dev-api
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3005:3005
    container_name: 'api'